sudo: false

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
    #  - "3.7"

install:
  - python setup.py install
  - pip install nose coverage mypy flake8 coveralls

script:
  - nosetests --config="" --cover-package=yaslha --with-coverage
  - mypy --strict yaslha/*.py
  - flake8 --max-line-length=120 .
  - coveralls
