sudo: false
cache: pip
language: python

before_install:
  - pip install poetry

install:
  - poetry install --develop=yaslha

stages:
  - test
  - typecheck
  - linting

script:
  - nosetests --config="" --cover-package=yaslha --with-coverage
  - coveralls

jobs:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial

    - stage: typecheck
      python: "3.6"
      script:
        - mypy --strict yaslha/*.py

    - stage: lint
      python: "3.6"
      script:
        - flake8 --max-line-length=120
