sudo: false
cache: pip
language: python

branches:
  only:
    - master
    - development

before_install:
  - pip install poetry

install:
  - poetry --version
  - poetry install -vvv

stages:
  - test
  - typecheck
#  - linting

script:
  - nosetests -s -d

after_success:
  - coveralls

jobs:
  include:
    - python: "3.7"
    - python: "3.9"

    - stage: typecheck
      python: "3.9"
      script:
        - mypy -p yaslha

#    - stage: linting
#      python: "3.6"
#      script:
#        - flake8 yaslha
