name: Test

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  perform-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.10' ]
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python-version }}
    name: Test on Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Set up Dependencies
        run: poetry install --no-interaction --no-root
      - name: Run test
        id: run
        run: |
          source .venv/bin/activate
          poetry run pytest --junit-xml=pytest_${{ matrix.python-version }}.xml --cov --cov-report=xml
        continue-on-error: true
      - name: Run coverage
        if: ${{ steps.run.outcome == 'success' }}
        uses: codecov/codecov-action@v2
        with:
          env_vars: PYTHON
        continue-on-error: true
      - name: Run Type-check
        if: ${{ steps.run.outcome == 'success' && matrix.python-version == '3.10' }}
        run: |
          source .venv/bin/activate
          mypy -p yaslha --junit-xml=mypy_${{ matrix.python-version }}.xml
        continue-on-error: true
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Result (Python ${{ matrix.python-version }})
          path: '*.xml'

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: perform-test
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: |
            artifacts/**/pytest_*.xml
            artifacts/**/mypy_*.xml
